version: "3.8"

services:
  lavalink:
    # pin the image version to Lavalink v4
    #image: ghcr.io/lavalink-devs/lavalink:4
    # Had to downgrade image version to v3 to get it working with Discord-MusicBot-v5
    image: ghcr.io/lavalink-devs/lavalink:3
    container_name: lavalink
    restart: unless-stopped
    environment:
      # set Java options here
      - _JAVA_OPTIONS=-Xmx2G
      # set lavalink server port (default: 2333)
      - SERVER_PORT=1750
      # set password for lavalink
      - LAVALINK_SERVER_PASSWORD=<REDACTED>
    volumes:
      # mount application.yml from the same directory or use environment variables
      - ./application.yml:/opt/Lavalink/application.yml
      # persist plugins between restarts, make sure to set the correct permissions (user: 322, group: 322)
      - ./plugins/:/opt/Lavalink/plugins/
    networks:
      - lavalink
    expose:
      # lavalink exposes port 2333 to connect to for other containers (this is for documentation purposes only)
      - 1750
    ports:
      # you only need this if you want to make your lavalink accessible from outside of containers
      - "127.0.0.1:1750:1750"
networks:
  # create a lavalink network you can add other containers to, to give them access to Lavalink
  lavalink:
    name: lavalink
